
title: EF-S 18
email: gutabereket@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A series of random photos mostly of nature
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bgutapix.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: bereket-guta
github_username:  bguta
twitter_username: bereketgvta

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
